options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: 'print-branch'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "********************"
          echo "Branch: $BRANCH_NAME"
          echo "********************"
          
  - id: tf-fmt
    name: 'hashicorp/terraform:1.14'
    entrypoint: sh
    dir: terraform
    args:
      - '-c'
      - terraform fmt -check -recursive
      
  - id: 'tf-init'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |

        terraform init -input=false 

  - id: 'tf-validate'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform validate

  - id: tfsec
    name: aquasec/tfsec:latest
    dir: terraform
    entrypoint: sh
    args:
        - '-c'
        - |
            tfsec -m HIGH .
        
  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
       set -e
       TFPLAN="tfplan-${BRANCH_NAME}-${SHORT_SHA}"
       terraform plan -input=false -out="${TFPLAN}"

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo " Applying Terraform on protected branch: $BRANCH_NAME"
            terraform apply "${TFPLAN}" -auto-approve -input=false 
          else
            echo "Skipping terraform apply on branch: $BRANCH_NAME"
          fi
