options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: 'print-branch'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "********************"
          echo "Branch: $BRANCH_NAME"
          echo "********************"

  - id: 'tf-init'
    name: 'hashicorp/terraform:1.6'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform init -input=false

  - id: 'tf-validate'
    name: 'hashicorp/terraform:1.6'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform validate

 - id: tfsec
   name: aquasec/tfsec:latest
   dir: terraform
   entrypoint: sh
   args:
     - '-c'
     - |
        tfsec .
        
  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.6'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform plan -input=false

  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.6'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform apply -auto-approve -input=false
