options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
 _ENV: dev  
# -------------------------
# Print the current branch
# -------------------------
steps:
  - id: 'print-branch'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "********************"
          echo "Branch: $BRANCH_NAME"
          echo "********************"
# -------------------------
# Terraform fmt
# -------------------------        
  - id: tf-fmt
    name: 'hashicorp/terraform:1.14'
    entrypoint: sh
    dir: terraform
    args:
      - '-c'
      - terraform fmt -check -recursive
# -------------------------
# Terraform Init
# -------------------------      
  - id: 'tf-init'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
         terraform init -input=false \
         -backend-config="prefix=env/${_ENV}"

# -------------------------
# Workspace Select/Create
# -------------------------
  - id: tf-workspace
    name: hashicorp/terraform:1.14
    dir: terraform
    entrypoint: sh
    args:
      - -c
      - |
        terraform workspace select "${_ENV}" \
         || terraform workspace new "${_ENV}"

# -------------------------
# Validate
# -------------------------      
  - id: 'tf-validate'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform validate
# -------------------------
# Security check
# -------------------------
  - id: tfsec
    name: aquasec/tfsec:latest
    dir: terraform
    entrypoint: sh
    args:
        - '-c'
        - |
            tfsec -m HIGH .
# -------------------------
# Create Plan
# -------------------------        
  - id: 'tf-plan'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        substitutions:
         _TFPLAN="tfplan-${BRANCH_NAME}-${SHORT_SHA}"
        terraform plan -out="$_TFPLAN"
# -------------------------
# Apply the existing plan
# -------------------------
  - id: 'tf-apply'
    name: 'hashicorp/terraform:1.14'
    dir: terraform
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo " Applying Terraform on protected branch: $BRANCH_NAME"
            terraform apply -auto-approve "$_TFPLAN"
          else
            echo "Skipping terraform apply on branch: $BRANCH_NAME"
          fi
